apiVersion: v1
kind: Pod
metadata:
  name: test-signed-quay
  namespace: default
spec:
  containers:
  - name: test-signed-quay
    image: quay.io/cwangvt/test-image-signing:latest-signed
    imagePullPolicy: Always

