apiVersion: v1
kind: Pod
metadata:
  name: test-fakesigned-quay
  namespace: default
spec:
  containers:
  - name: test-fakesigned-quay
    image: quay.io/cwangvt/test-image-signing:latest-fakesigned
    imagePullPolicy: Always

